config/routes.rb
Rails.application.routes.draw do
  

  devise_scope :user do
    get "/signin" => "devise/sessions#new" # custom path to login/sign_in
    get "/signup" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users
  get '/home',   to: 'restaurant#home'
  get '/restaurant/new', to: 'restaurant#form' #admin
  get '/restaurant/:id_restaurant',  to: 'restaurant#show' 
  get '/restaurant/:id_restaurant/edit', to: 'restaurant#form' #admin
  post '/restaurant/:id_restaurant/reservation', to: 'restaurant#reservation'
  get '/restaurants', to: 'restaurant#list' #admin
  post '/restaurant', to: 'restaurant#create'
  put '/restaurant/:id_restaurant', to: 'restaurant#update'
  get '/restaurant/:id_restaurant/destroy', to: 'restaurant#destroy'

  post '/opening/:id_restaurant/add', to: 'opening#add'
  get '/opening/:id_opening/destroy', to: 'opening#destroy'

  post '/carousel/:id_restaurant/add', to: 'carousel#add'
  get '/carousel/:id_carousel/destroy', to: 'carousel#destroy'

#  post '/restaurant/:id_restaurant/update', to: 'restaurant#edit'
  root 'restaurant#home'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController
    before_action :authenticate_user!, :except => [:home, :show, :reservation]

    def home
        @restaurants = Restaurant.take 5
    end

    def list
        @id = current_user.id
        @restaurants = Restaurant.where(user_id: @id)
    end

    def show
        @restaurant = Restaurant.find params[:id_restaurant]

        @carousels = Carousel.where(restaurant_id: params[:id_restaurant])

        @openings = Opening.where(restaurant_id: params[:id_restaurant])

        opened = false
        @openings.each do |opening|
            if Time.now.hour >= opening.open_at && Time.now.hour < opening.close_at
                opened = true 
            end
        end
        @isOpen = opened
    end

    def reservation
        res = Reservation.new
        res.when = DateTime.new(2017, Time.now.month, Time.now.day + params[:when_date].to_i, params[:when_hour].to_i, 0, 0)
        res.phone = params[:phone]
        res.person = params[:person].to_i
        res.restaurant_id = params[:id_restaurant].to_i
        @id = res.restaurant_id
        @result = res.save()
    end

    def form
        @isEdit = false
        if params[:id_restaurant]
            @isEdit = true
            @restaurant = Restaurant.find params[:id_restaurant]
            @openings = Opening.where(restaurant_id: params[:id_restaurant])
            @reservations = Reservation.where(restaurant_id: params[:id_restaurant])
            @carousel = Carousel.where(restaurant_id: params[:id_restaurant])
        end
    end

    def create
        resto = Restaurant.new
        resto.name = params[:name]
        resto.logo = params[:logo]
        resto.city = params[:city]
        resto.zipcode = params[:zipcode]
        resto.address = params[:address]
        resto.phone = params[:phone]
        resto.place = params[:place]
        resto.menu = params[:menu]
        resto.user_id = current_user.id
        @saved = resto.save()
    end

    def update
        resto = Restaurant.find params[:id_restaurant]
        resto.name = params[:name]
        resto.logo = params[:logo]
        resto.city = params[:city]
        resto.zipcode = params[:zipcode]
        resto.address = params[:address]
        resto.phone = params[:phone]
        resto.place = params[:place]
        resto.menu = params[:menu]
		@saved = resto.save()
		@restaurant_id = params[:id_restaurant]
    end

    def destroy
        resto = Restaurant.find params[:id_restaurant]
        if current_user.id == resto.user_id
            resto.destroy
        end
    end
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/views/restaurant/create.html.erb
<script>
document.location.href="/restaurants"
</script>

app/views/restaurant/destroy.html.erb
<script>
document.location.href="/restaurants"
</script>

app/views/restaurant/form.html.erb
<div class="container">
    <h1>
        <%= @isEdit ? 'Editer ' + @restaurant.name : 'Créer un site pour votre restaurant' %>
        <% if @isEdit %>
            <%= link_to "Prévisualiser", '/restaurant/' + @restaurant.id.to_s, :class => "btn btn-primary" %>
        <% end %>
        <span style="float:right; font-size: 0.7rem"><%= link_to "Retour a la liste", "/restaurants" %></span>
    </h1>

    <div class="row">
        <div class="col-<%= @isEdit ? 6 : 12 %>">
            <%= form_tag('/restaurant' + (@isEdit ? '/' + @restaurant.id.to_s : ""), method: @isEdit ? 'put' : 'post') do %>
                <div class="form-group">
                    <label>Nom du restaurant</label>
                    <input class="form-control" value="<%= @isEdit ? @restaurant.name : '' %>" name="name" id="name" placeholder="L'Oasis">
                </div>
                <div class="form-group">
                    <label>Logo URL</label>
                    <input class="form-control" name="logo" value="<%= @isEdit ? @restaurant.logo : '' %>">
                </div>
                <div class="form-group">
                    <label>Ville</label>
                    <input class="form-control" name="city" id="city" placeholder="Anses d'arlet" value="<%= @isEdit ? @restaurant.city : '' %>">
                </div>
                <div class="form-group">
                    <label>Code Postal</label>
                    <input class="form-control" name="zipcode" id="zipcode" placeholder="97217" value="<%= @isEdit ? @restaurant.zipcode : '' %>">
                </div>
                <div class="form-group">
                    <label>Adresse</label>
                    <input class="form-control" name="address" id="address" placeholder="" value="<%= @isEdit ? @restaurant.address : '' %>">
                </div>
                <div class="form-group">
                    <label>Téléphone du restaurant</label>
                    <input class="form-control" name="phone" id="phone" placeholder="" value="<%= @isEdit ? @restaurant.phone : '' %>">
                </div>
                <div class="form-group">
                    <label>Nombre de place</label>
                    <input class="form-control" name="place" id="place" placeholder="45" value="<%= @isEdit ? @restaurant.place : '' %>">
                </div>
                <div class="form-group">
                    <label>Lien vers une image du menu</label>
                    <input class="form-control" name="menu" id="menu" placeholder="" value="<%= @isEdit ? @restaurant.menu : '' %>">
                </div>
                <%= submit_tag(@isEdit ? 'Sauvegarder' : "Créer", :class => "btn btn-primary") %>
            <% end %>
        </div>
        <% if @isEdit %>
            <div class="col-6">
                <h3>Horaire actuelle</h3>
                <ul class="list-group">
                <% @openings.each_with_index do |opening, i| %>
                    <li class="list-group-item">
                        De <%= opening.open_at %>h a <%= opening.close_at %>h
                        <span style="float: right"><%= link_to "X", "/opening/" + opening.id.to_s + "/destroy" %></span>
                    </li>
                <% end %>
                </ul>
                <h3>Ajouter une nouvelle plage horaire</h3>
                <%= form_tag("/opening/" + @restaurant.id.to_s + "/add", method: 'post') do %>
                    <div class="form-group">
                        <label>Heure douverture</label>
                        <input class="form-control" name="open_at" id="open_at" placeholder="18">
                    </div>
                    <div class="form-group">
                        <label>Heure de fermeture</label>
                        <input class="form-control" name="close_at" id="close_at" placeholder="23">
                    </div>
                    <%= submit_tag("Ajouter", :class => "btn btn-primary") %>
                <% end %>
                <hr>
                <h3>Reservations en cours</h3>
                <ul class="list-group">
                    <% @reservations.each do |reservation| %>
                    <li class="list-group-item">
                        <span style="float: right; font-size: 0.7rem">
                            <div style="color: green">
                                valider
                            </div>
                            <div style="color: red">
                                refuser
                            </div>
                        </span>
                        <span style="display: block">
                            <%= reservation.person %> personne<%= reservation.person > 1 ? 's' : '' %>
                            le <%= reservation.when.strftime('%e %B a %l:%M %p') %>
                        </span>
                        <span style="display: block">
                            Contact: <%= reservation.phone %>
                        </span>
                    </li>
                    <% end %>
                </ul>
			</div>
            <div class="col-12">
                <h3>Images principales</h3>
                <ul class="list-group">
                <% @carousel.each_with_index do |carousel, i| %>
                    <li class="list-group-item">
						<img style="float:left; max-width: 300px; max-height: 150px;" src="<%= carousel.image %>">
						<span style="float: right"><%= link_to "X", "/carousel/" + carousel.id.to_s + "/destroy" %></span>
						<div><strong>Titre:</strong> <%= carousel.title && carousel.title != '' ? carousel.title : 'non renseigné' %></div>
						<div><strong>Baseline:</strong> <%= carousel.baseline && carousel.baseline != '' ? carousel.baseline : 'non renseigné' %></div>
						<div><strong>Couleur texte:</strong> <%= carousel.color && carousel.color != ''? carousel.color : 'non renseigné' %></label>
						<div><strong>Offset:</strong> <%= carousel.offset && carousel.offset != '' ? carousel.offset : 'non renseigné' %></div>
	                </li>
    	        <% end %>
        	    </ul>

				<h3>Ajouter une image principal</h3> #add image carousel
                <%= form_tag("/carousel/" + @restaurant.id.to_s + "/add", method: 'post') do %>
                    <div class="form-group">
                        <label>Image URL</label>
                        <input class="form-control" name="image" id="image" placeholder="http://...">
                    </div>
                    <div class="form-group">
                        <label>Titre</label>
                        <input class="form-control" name="title" id="title" placeholder="Bienvenue a l'Oasis">
                    </div>
                    <div class="form-group">
                        <label>baseline</label>
                        <input class="form-control" name="baseline" id="baseline" placeholder="Plat locaux gastronomique">
                    </div>
                    <div class="form-group">
                        <label>Couleur du texte (RGB)</label>
                        <input class="form-control" name="color" id="color" placeholder="#123123">
                    </div>
                    <div class="form-group">
                        <label>Offset</label>
                        <input class="form-control" name="offset" id="offset" placeholder="-150">
                    </div>

                    <%= submit_tag("Ajouter", :class => "btn btn-primary") %>
                <% end %>
			</div>
		<% end %>
    </div>
</div>

app/views/restaurant/home.html.erb
<div class="container">
    <div class="jumbotron">
        <h1>Restaurant builder</h1>

        <h3>Créez votre site de restaurant en ligne en quelque minute!</h3>
        <div style="margin-top: 30px;">
            <% if user_signed_in? %>
            <%= link_to "Acceder a mon compte", "/restaurants", :class => "btn" %>
            <% else %>
            <%= link_to "Creez votre compte maintenant !", new_user_registration_path, :class => "btn btn-primary" %>
            <%= link_to "Acceder a mon compte", signin_path, :class => "btn" %>
            <% end %>
        </div>
    </div>
    <h3>Ces restaurants nous font déjà confiance:<h3>
    <div id="main-container">
        <% @restaurants.each do |restaurant| %>
            <p><%= link_to restaurant.name, "/restaurant/" + restaurant.id.to_s %></p>
        <% end %>
    </div>
</div>

app/views/restaurant/list.html.erb
<div class="container">
    <h1>
        <span style="float:right; font-size: 0.7rem;">
            <%= link_to "Deconnexion", destroy_user_session_path, method: 'delete' %>
        </span>
        Liste de vos restaurants
    </h1>
    <% if @restaurants.count > 0 %>
        <ul class="list-group">
        <% @restaurants.each do |restaurant| %>
            <li class="list-group-item">
                <%= link_to restaurant.name + " situé à " + restaurant.city, "/restaurant/" + restaurant.id.to_s + "/edit" %>

                <span style="float: right"><%= link_to "X", "/restaurant/" + restaurant.id.to_s + "/destroy" %></span>
            </li>
        <% end %>
    <% else %>
        <span>0 restaurant enregistré.</span>
    <% end %>
    <div style="margin-top: 20px;">
        <%= link_to "Créer un restaurant", "/restaurant/new", :class => "btn btn-primary" %>
        <%= link_to "Retour a la homepage", root_path, :class => "btn" %>
    </div>
</div>

app/views/restaurant/reservation.html.erb
<h1>Merci d'avoir réserver une table !<h1>
<h3>Nous validerons votre réservation dans les plus bref delais et vous enverrons une confirmation sur votre téléphone par SMS.</h3>
<a href="/restaurant/<%= @id %>" class="btn btn-primary">
    Back to restaurant page
</button>

app/views/restaurant/show.html.erb
<%= render 'components/header_restaurant' %>

<%= render :partial => 'components/carousel_restaurant', :locals => { :carousels => @carousels } %>

<div class="container" style="border-left: 1px solid #DDD; border-right: 1px solid #DDD">
    <div class="row" id="carte">
        <div class="col-8" style="border-right: 1px solid #DDD; text-align: center">
            <img src="<%= @restaurant.menu %>" alt="menu">
        </div>
        <div class="col-4">
            <div id="opening">
                <div>
                    Actuellement:

                    <% if @isOpen %>
                    <span style="background-color: green; color: white; border-radius: 3px;">OUVERT</span>
                    <% else %>
                    <span style="background-color: red; color: white; border-radius: 3px;">FERMÉ</span>
                    <% end %>
                </div>

                Ouvert de 
                <% @openings.each_with_index do |opening, index| %>
                    <% if index == @openings.count - 1 && index > 0 %>
                        et de
                    <% end %>
                    <% if index > 0 && index < @openings.count - 1 %>
                        , de
                    <% end %>

                    <%= opening.open_at %>h à <%= opening.close_at %>h
                <% end %>
            </div>
            <div>
                <i class="fa fa-maps"></i>Situé à <%= @restaurant.city %> <%= @restaurant.zipcode %>
            </div>
            <div id="map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d482.85945616965483!2d-61.082007095980224!3d14.49182715259781!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x68d886e7647a4dc1!2sKaban&#39;+Ylan!5e0!3m2!1sen!2s!4v1505513115509" style="width:100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
            <div>
                <button class="reserve-now btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Réservez maintenant
                </button>
            </div>
            <div>
                <i class="fa fa-phone"></i><%= @restaurant.phone %>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <%= form_tag("/restaurant/" + @restaurant.id.to_s + "/reservation", method: "post") do %>
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Reservation</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Pour quand voulez vous reserver ?</label>
                        <select name="when_date" id="when_date">
                            <% 5.times.each do |i| %>
                                <option value="<%= i %>"><%= (Time.now + i.day).strftime('%e %B') %></option>
                            <% end %>
                        </select>
                        <select name="when_hour" id="when_hour">
                            <% @openings.each do |opening| %>
                                <% (opening.close_at - opening.open_at).times.each do |i| %>
                                    <option value="<%= opening.open_at + i %>"><%= opening.open_at + i %>h</option>
                                <% end %>
                            <% end %>
                        </select>
                    </div>
                    <div class="row">
                        <div class="form-group col-8">
                            <label>Sur quel numéro pouvons-nous valider la reservation ?</label>
                            <input class="form-control" name="phone" id="phone" placeholder="06 96 ...">
                        </div>
                        <div class="form-group col-4">
                            <label>Pour combien de personnes?</label>
                            <select name="person" id="person" class="form-control">
                                <% 12.times.each do |i| %>
                                    <option value="<%= i + 1 %>"><%= i + 1 %> Personne<%= i + 1 > 1 ? 's' : '' %></option>
                                <% end %>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                    <%= submit_tag("Reserver") %>
                </div>
            </div>
        <% end %>
    </div>
</div>

<% if current_user && current_user.id == @restaurant.user_id %>
<div style="background-color: #343a40 !important;position:fixed; bottom:0; left:0; border-top-right-radius: 10px; width: 150px; height: 50px; text-align: center;">
    <span style="position: relative; top: 15px;"><%= link_to "Admin panel", "/restaurant/" + @restaurant.id.to_s + "/edit", :style => "color: white" %></span>
</div>
<% end %>
<%= render 'components/footer_restaurant' %>

app/views/restaurant/update.html.erb
<script>
document.location.href="/restaurant/<%= @restaurant_id %>/edit"
</script>